import type { Collection } from '@/app/lib/definitions';
import type { GalleryItem } from '@/app/lib/gallery';
import type { MediaItem } from '@/app/lib/definitions';

const photoCover = 'from-emerald-400/35 via-slate-900/70 to-slate-950';
const videoCover = 'from-sky-400/35 via-slate-900/70 to-slate-950';
const mixedCover = 'from-violet-400/35 via-slate-900/70 to-slate-950';

export const getFallbackItems = (): GalleryItem[] => [
  {
    id: 'fallback-1',
    type: 'photo',
    src: '/hero-desktop.png',
    title: 'front.data.fallback.1.title',
    description: 'front.data.fallback.1.description',
    camera: 'Sony A7R V',
    maker: 'Sony',
    lens: 'FE 24-70mm GM II',
    exposure: 1 / 125,
    aperture: 2.8,
    iso: 100,
    focalLength: 35,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 1920,
    height: 1080,
  },
  {
    id: 'fallback-2',
    type: 'photo',
    src: '/hero1.jpg',
    title: 'front.data.fallback.2.title',
    description: 'front.data.fallback.2.description',
    camera: 'Fujifilm X-T5',
    maker: 'Fujifilm',
    lens: 'XF 33mm f/1.4',
    exposure: 1 / 60,
    aperture: 1.4,
    iso: 800,
    focalLength: 33,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 4000,
    height: 6000,
  },
  {
    id: 'fallback-3',
    type: 'photo',
    src: '/hero2.jpg',
    title: 'front.data.fallback.3.title',
    description: 'front.data.fallback.3.description',
    camera: 'Leica Q3',
    maker: 'Leica',
    lens: 'Summilux 28mm f/1.7',
    exposure: 1 / 500,
    aperture: 5.6,
    iso: 200,
    focalLength: 28,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 6000,
    height: 4000,
  },
  {
    id: 'fallback-4',
    type: 'photo',
    src: '/hero3.jpg',
    title: 'front.data.fallback.4.title',
    description: 'front.data.fallback.4.description',
    camera: 'Canon EOS R5',
    maker: 'Canon',
    lens: 'RF 50mm f/1.2L',
    exposure: 1 / 200,
    aperture: 1.2,
    iso: 100,
    focalLength: 50,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 5000,
    height: 3333,
  },
  {
    id: 'fallback-5',
    type: 'photo',
    src: '/hero4.jpg',
    title: 'front.data.fallback.5.title',
    description: 'front.data.fallback.5.description',
    camera: 'Nikon Z8',
    maker: 'Nikon',
    lens: 'NIKKOR Z 14-24mm f/2.8',
    exposure: 1 / 400,
    aperture: 4,
    iso: 64,
    focalLength: 14,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 8256,
    height: 5504,
  },
];

export const featuredCollections: Collection[] = [
  {
    id: 'fc-01',
    type: 'photo',
    title: 'front.data.featured.fc-01.title',
    cover: photoCover,
    count: 28,
    description: 'front.data.featured.fc-01.description',
    tags: ['front.data.featured.fc-01.tags.0', 'front.data.featured.fc-01.tags.1', 'front.data.featured.fc-01.tags.2'],
  },
  {
    id: 'fc-02',
    type: 'video',
    title: 'front.data.featured.fc-02.title',
    cover: videoCover,
    count: 12,
    description: 'front.data.featured.fc-02.description',
    tags: ['front.data.featured.fc-02.tags.0', 'front.data.featured.fc-02.tags.1', 'front.data.featured.fc-02.tags.2'],
  },
  {
    id: 'fc-03',
    type: 'photo',
    title: 'front.data.featured.fc-03.title',
    cover: mixedCover,
    count: 19,
    description: 'front.data.featured.fc-03.description',
    tags: ['front.data.featured.fc-03.tags.0', 'front.data.featured.fc-03.tags.1', 'front.data.featured.fc-03.tags.2'],
  },
];

export const photoCollections: Collection[] = [
  {
    id: 'pc-01',
    type: 'photo',
    title: 'front.data.photo.pc-01.title',
    cover: photoCover,
    count: 24,
    description: 'front.data.photo.pc-01.description',
    tags: ['front.data.photo.pc-01.tags.0', 'front.data.photo.pc-01.tags.1'],
  },
  {
    id: 'pc-02',
    type: 'photo',
    title: 'front.data.photo.pc-02.title',
    cover: mixedCover,
    count: 17,
    description: 'front.data.photo.pc-02.description',
    tags: ['front.data.photo.pc-02.tags.0', 'front.data.photo.pc-02.tags.1'],
  },
  {
    id: 'pc-03',
    type: 'photo',
    title: 'front.data.photo.pc-03.title',
    cover: photoCover,
    count: 14,
    description: 'front.data.photo.pc-03.description',
    tags: ['front.data.photo.pc-03.tags.0', 'front.data.photo.pc-03.tags.1'],
  },
  {
    id: 'pc-04',
    type: 'photo',
    title: 'front.data.photo.pc-04.title',
    cover: mixedCover,
    count: 21,
    description: 'front.data.photo.pc-04.description',
    tags: ['front.data.photo.pc-04.tags.0', 'front.data.photo.pc-04.tags.1'],
  },
  {
    id: 'pc-05',
    type: 'photo',
    title: 'front.data.photo.pc-05.title',
    cover: photoCover,
    count: 12,
    description: 'front.data.photo.pc-05.description',
    tags: ['front.data.photo.pc-05.tags.0', 'front.data.photo.pc-05.tags.1'],
  },
  {
    id: 'pc-06',
    type: 'photo',
    title: 'front.data.photo.pc-06.title',
    cover: mixedCover,
    count: 16,
    description: 'front.data.photo.pc-06.description',
    tags: ['front.data.photo.pc-06.tags.0', 'front.data.photo.pc-06.tags.1'],
  },
];

export const videoCollections: Collection[] = [
  {
    id: 'vc-01',
    type: 'video',
    title: 'front.data.video.vc-01.title',
    cover: videoCover,
    count: 8,
    description: 'front.data.video.vc-01.description',
    tags: ['front.data.video.vc-01.tags.0', 'front.data.video.vc-01.tags.1'],
  },
  {
    id: 'vc-02',
    type: 'video',
    title: 'front.data.video.vc-02.title',
    cover: mixedCover,
    count: 5,
    description: 'front.data.video.vc-02.description',
    tags: ['front.data.video.vc-02.tags.0', 'front.data.video.vc-02.tags.1'],
  },
  {
    id: 'vc-03',
    type: 'video',
    title: 'front.data.video.vc-03.title',
    cover: videoCover,
    count: 6,
    description: 'front.data.video.vc-03.description',
    tags: ['front.data.video.vc-03.tags.0', 'front.data.video.vc-03.tags.1'],
  },
  {
    id: 'vc-04',
    type: 'video',
    title: 'front.data.video.vc-04.title',
    cover: mixedCover,
    count: 7,
    description: 'front.data.video.vc-04.description',
    tags: ['front.data.video.vc-04.tags.0', 'front.data.video.vc-04.tags.1'],
  },
];

export const galleryMedia: MediaItem[] = [
  {
    id: 'gm-01',
    type: 'photo',
    title: 'front.data.gallery.gm-01.title',
    cover: photoCover,
    tags: ['front.data.gallery.gm-01.tags.0', 'front.data.gallery.gm-01.tags.1'],
    createdAt: '2024-10-08',
    collectionId: 'pc-06',
  },
  {
    id: 'gm-02',
    type: 'video',
    title: 'front.data.gallery.gm-02.title',
    cover: videoCover,
    tags: ['front.data.gallery.gm-02.tags.0', 'front.data.gallery.gm-02.tags.1'],
    createdAt: '2024-11-22',
    collectionId: 'vc-02',
  },
  {
    id: 'gm-03',
    type: 'photo',
    title: 'front.data.gallery.gm-03.title',
    cover: mixedCover,
    tags: ['front.data.gallery.gm-03.tags.0', 'front.data.gallery.gm-03.tags.1'],
    createdAt: '2024-07-02',
    collectionId: 'pc-02',
  },
  {
    id: 'gm-04',
    type: 'video',
    title: 'front.data.gallery.gm-04.title',
    cover: videoCover,
    tags: ['front.data.gallery.gm-04.tags.0', 'front.data.gallery.gm-04.tags.1'],
    createdAt: '2024-09-14',
    collectionId: 'vc-04',
  },
  {
    id: 'gm-05',
    type: 'photo',
    title: 'front.data.gallery.gm-05.title',
    cover: photoCover,
    tags: ['front.data.gallery.gm-05.tags.0', 'front.data.gallery.gm-05.tags.1'],
    createdAt: '2024-04-11',
    collectionId: 'pc-01',
  },
  {
    id: 'gm-06',
    type: 'photo',
    title: 'front.data.gallery.gm-06.title',
    cover: mixedCover,
    tags: ['front.data.gallery.gm-06.tags.0', 'front.data.gallery.gm-06.tags.1'],
    createdAt: '2024-12-01',
    collectionId: 'pc-03',
  },
  {
    id: 'gm-07',
    type: 'video',
    title: 'front.data.gallery.gm-07.title',
    cover: videoCover,
    tags: ['front.data.gallery.gm-07.tags.0', 'front.data.gallery.gm-07.tags.1'],
    createdAt: '2024-06-20',
    collectionId: 'vc-01',
  },
  {
    id: 'gm-08',
    type: 'photo',
    title: 'front.data.gallery.gm-08.title',
    cover: photoCover,
    tags: ['front.data.gallery.gm-08.tags.0', 'front.data.gallery.gm-08.tags.1'],
    createdAt: '2024-02-02',
    collectionId: 'pc-01',
  },
  {
    id: 'gm-09',
    type: 'video',
    title: 'front.data.gallery.gm-09.title',
    cover: mixedCover,
    tags: ['front.data.gallery.gm-09.tags.0', 'front.data.gallery.gm-09.tags.1'],
    createdAt: '2024-03-18',
    collectionId: 'vc-03',
  },
];
