import type { Collection } from '@/app/lib/definitions';
import type { GalleryItem } from '@/app/lib/gallery';
import type { MediaItem } from '@/app/lib/definitions';

const photoCover = 'from-emerald-400/35 via-slate-900/70 to-slate-950';
const videoCover = 'from-sky-400/35 via-slate-900/70 to-slate-950';
const mixedCover = 'from-violet-400/35 via-slate-900/70 to-slate-950';

export const getFallbackItems = (): GalleryItem[] => [
  {
    id: 'fallback-1',
    type: 'photo',
    src: '/hero-desktop.png',
    title: 'Dashboard Preview',
    description: 'A comprehensive view of the dashboard interface.',
    camera: 'Sony A7R V',
    maker: 'Sony',
    lens: 'FE 24-70mm GM II',
    exposure: 1 / 125,
    aperture: 2.8,
    iso: 100,
    focalLength: 35,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 1920,
    height: 1080,
  },
  {
    id: 'fallback-2',
    type: 'photo',
    src: '/hero1.jpg',
    title: 'Neon Nights',
    description: 'Vibrant city lights reflecting in the rain.',
    camera: 'Fujifilm X-T5',
    maker: 'Fujifilm',
    lens: 'XF 33mm f/1.4',
    exposure: 1 / 60,
    aperture: 1.4,
    iso: 800,
    focalLength: 33,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 4000,
    height: 6000,
  },
  {
    id: 'fallback-3',
    type: 'photo',
    src: '/hero2.jpg',
    title: 'Urban Geometry',
    description: 'Modern architectural lines and shadows.',
    camera: 'Leica Q3',
    maker: 'Leica',
    lens: 'Summilux 28mm f/1.7',
    exposure: 1 / 500,
    aperture: 5.6,
    iso: 200,
    focalLength: 28,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 6000,
    height: 4000,
  },
  {
    id: 'fallback-4',
    type: 'photo',
    src: '/hero3.jpg',
    title: 'Serene Nature',
    description: 'Soft morning light filtering through the trees.',
    camera: 'Canon EOS R5',
    maker: 'Canon',
    lens: 'RF 50mm f/1.2L',
    exposure: 1 / 200,
    aperture: 1.2,
    iso: 100,
    focalLength: 50,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 5000,
    height: 3333,
  },
  {
    id: 'fallback-5',
    type: 'photo',
    src: '/hero4.jpg',
    title: 'Ocean Horizon',
    description: 'A calm sunset over the endless ocean.',
    camera: 'Nikon Z8',
    maker: 'Nikon',
    lens: 'NIKKOR Z 14-24mm f/2.8',
    exposure: 1 / 400,
    aperture: 4,
    iso: 64,
    focalLength: 14,
    dateShot: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    width: 8256,
    height: 5504,
  },
];

export const featuredCollections: Collection[] = [
  {
    id: 'fc-01',
    type: 'photo',
    title: '暮色星港',
    cover: photoCover,
    count: 28,
    description: '城市与星光交界的长曝光故事。',
    tags: ['夜景', '长曝光', '城市'],
  },
  {
    id: 'fc-02',
    type: 'video',
    title: '轨道碎光',
    cover: videoCover,
    count: 12,
    description: '节奏化剪辑的宇宙旅程片段。',
    tags: ['短片', '配乐', '运动'],
  },
  {
    id: 'fc-03',
    type: 'photo',
    title: '极光档案',
    cover: mixedCover,
    count: 19,
    description: '冰原与光带的冷色调拼贴。',
    tags: ['自然', '冷色', '极光'],
  },
];

export const photoCollections: Collection[] = [
  {
    id: 'pc-01',
    type: 'photo',
    title: '雾面海岸',
    cover: photoCover,
    count: 24,
    description: '雾气、潮汐与灰度层次的平衡。',
    tags: ['海岸', '灰度'],
  },
  {
    id: 'pc-02',
    type: 'photo',
    title: '夜行光轨',
    cover: mixedCover,
    count: 17,
    description: '霓虹与车流构成的光线地图。',
    tags: ['光轨', '霓虹'],
  },
  {
    id: 'pc-03',
    type: 'photo',
    title: '晨曦静域',
    cover: photoCover,
    count: 14,
    description: '黎明时分的柔光与留白。',
    tags: ['日出', '极简'],
  },
  {
    id: 'pc-04',
    type: 'photo',
    title: '镜像森林',
    cover: mixedCover,
    count: 21,
    description: '雨后森林的折射与倒影。',
    tags: ['森林', '倒影'],
  },
  {
    id: 'pc-05',
    type: 'photo',
    title: '线性实验',
    cover: photoCover,
    count: 12,
    description: '几何构图的极简实验室。',
    tags: ['几何', '线条'],
  },
  {
    id: 'pc-06',
    type: 'photo',
    title: '薄暮航线',
    cover: mixedCover,
    count: 16,
    description: '以空气感描绘的长航轨迹。',
    tags: ['旅行', '云层'],
  },
];

export const videoCollections: Collection[] = [
  {
    id: 'vc-01',
    type: 'video',
    title: '切片宇宙',
    cover: videoCover,
    count: 8,
    description: '多机位拼贴成的叙事。',
    tags: ['多机位', '叙事'],
  },
  {
    id: 'vc-02',
    type: 'video',
    title: '蓝光航标',
    cover: mixedCover,
    count: 5,
    description: '蓝色调色的情绪短片。',
    tags: ['情绪', '蓝调'],
  },
  {
    id: 'vc-03',
    type: 'video',
    title: '静默工坊',
    cover: videoCover,
    count: 6,
    description: '工作室日常的慢节奏观察。',
    tags: ['纪录', '慢镜'],
  },
  {
    id: 'vc-04',
    type: 'video',
    title: '磁场回声',
    cover: mixedCover,
    count: 7,
    description: '电子音乐驱动的视觉节拍。',
    tags: ['电子', '节拍'],
  },
];

export const galleryMedia: MediaItem[] = [
  {
    id: 'gm-01',
    type: 'photo',
    title: '零点云层',
    cover: photoCover,
    tags: ['冷调', '云层'],
    createdAt: '2024-10-08',
    collectionId: 'pc-06',
  },
  {
    id: 'gm-02',
    type: 'video',
    title: '引力回廊',
    cover: videoCover,
    tags: ['慢动作', '节奏'],
    createdAt: '2024-11-22',
    collectionId: 'vc-02',
  },
  {
    id: 'gm-03',
    type: 'photo',
    title: '幽光街区',
    cover: mixedCover,
    tags: ['街景', '霓虹'],
    createdAt: '2024-07-02',
    collectionId: 'pc-02',
  },
  {
    id: 'gm-04',
    type: 'video',
    title: '暗场节拍',
    cover: videoCover,
    tags: ['夜景', '节拍'],
    createdAt: '2024-09-14',
    collectionId: 'vc-04',
  },
  {
    id: 'gm-05',
    type: 'photo',
    title: '晨雾质感',
    cover: photoCover,
    tags: ['雾气', '质感'],
    createdAt: '2024-04-11',
    collectionId: 'pc-01',
  },
  {
    id: 'gm-06',
    type: 'photo',
    title: '极夜回声',
    cover: mixedCover,
    tags: ['极夜', '光晕'],
    createdAt: '2024-12-01',
    collectionId: 'pc-03',
  },
  {
    id: 'gm-07',
    type: 'video',
    title: '穿梭引擎',
    cover: videoCover,
    tags: ['运动', '剪辑'],
    createdAt: '2024-06-20',
    collectionId: 'vc-01',
  },
  {
    id: 'gm-08',
    type: 'photo',
    title: '静谧桅灯',
    cover: photoCover,
    tags: ['海岸', '蓝调'],
    createdAt: '2024-02-02',
    collectionId: 'pc-01',
  },
  {
    id: 'gm-09',
    type: 'video',
    title: '星屑轨迹',
    cover: mixedCover,
    tags: ['星光', '短片'],
    createdAt: '2024-03-18',
    collectionId: 'vc-03',
  },
];
