CREATE TABLE "video_metadata" (
	"file_id" integer PRIMARY KEY NOT NULL,
	"duration" double precision,
	"width" integer,
	"height" integer,
	"bitrate" integer,
	"fps" double precision,
	"frame_count" integer,
	"codec_video" varchar(64),
	"codec_video_profile" varchar(64),
	"pixel_format" varchar(64),
	"color_space" varchar(64),
	"color_range" varchar(64),
	"color_primaries" varchar(64),
	"color_transfer" varchar(64),
	"bit_depth" integer,
	"codec_audio" varchar(64),
	"audio_channels" integer,
	"audio_sample_rate" integer,
	"audio_bitrate" integer,
	"has_audio" boolean,
	"rotation" integer,
	"container_format" varchar(64),
	"container_long" varchar(255),
	"poster_time" double precision,
	"raw" jsonb
);
